RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 17:58:15,728 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:34111'
2023-04-04 17:58:15,730 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:40397'
2023-04-04 17:58:16,886 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-ews4qji5', purging
2023-04-04 17:58:16,887 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-1sy91v23', purging
2023-04-04 17:58:16,887 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 17:58:16,887 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 17:58:16,894 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 17:58:16,894 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 17:58:17,188 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 17:58:17,199 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 17:58:18,455 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:41227
2023-04-04 17:58:18,455 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:41227
2023-04-04 17:58:18,455 - distributed.worker - INFO -          dashboard at:        10.120.104.11:41727
2023-04-04 17:58:18,455 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 17:58:18,455 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,455 - distributed.worker - INFO -               Threads:                          1
2023-04-04 17:58:18,455 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 17:58:18,455 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-1mb81rox
2023-04-04 17:58:18,455 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-663ad21f-d0d9-4199-bb8a-e1558f9378b2
2023-04-04 17:58:18,455 - distributed.worker - INFO - Starting Worker plugin PreImport-dfdb0353-d692-499e-bd27-8353a4e78257
2023-04-04 17:58:18,455 - distributed.worker - INFO - Starting Worker plugin RMMSetup-53e505dc-5044-4dfc-874e-d8e037bf488d
2023-04-04 17:58:18,487 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:32779
2023-04-04 17:58:18,487 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:32779
2023-04-04 17:58:18,487 - distributed.worker - INFO -          dashboard at:        10.120.104.11:46423
2023-04-04 17:58:18,487 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 17:58:18,487 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,487 - distributed.worker - INFO -               Threads:                          1
2023-04-04 17:58:18,487 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 17:58:18,487 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-30sqk3kw
2023-04-04 17:58:18,488 - distributed.worker - INFO - Starting Worker plugin RMMSetup-dec01f86-f688-4427-9209-f2800eb5633f
2023-04-04 17:58:18,587 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,598 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 17:58:18,598 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,600 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 17:58:18,640 - distributed.worker - INFO - Starting Worker plugin PreImport-7a09e640-bf6f-4dd0-a378-f6bea4912ff8
2023-04-04 17:58:18,640 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-1a0292c3-e7a6-46ca-b26b-bb5a0247ae41
2023-04-04 17:58:18,641 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,652 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 17:58:18,653 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:58:18,655 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 17:58:34,723 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:58:34,727 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:58:35,543 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:58:35,543 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:58:36,171 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:58:36,179 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:58:36,187 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:58:36,193 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:58:44,720 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:58:44,732 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:58:52,643 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 17:58:52,643 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 17:58:52,650 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:58:52,650 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:59:02,561 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:02,562 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:03,012 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:03,012 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:05,291 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:05,293 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:07,355 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:07,356 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:07,557 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:07,557 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:11,255 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:11,255 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:11,466 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:11,466 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:14,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:14,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:15,181 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:15,182 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:18,680 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:18,681 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:18,887 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:18,891 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:22,386 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:22,386 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:22,594 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:22,595 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:26,100 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:26,103 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:26,178 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:26,178 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:29,001 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:29,001 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:31,005 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:59:31,006 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:18,969 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:18,971 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:18,975 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:01:18,975 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:01:19,174 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:19,174 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:19,175 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:01:19,175 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:01:19,438 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:01:19,439 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:01:19,641 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:01:19,642 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:01:29,308 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:29,309 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:01:35,360 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:32779. Reason: worker-handle-scheduler-connection-broken
2023-04-04 18:01:35,360 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:34111'. Reason: nanny-close
2023-04-04 18:01:35,361 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 18:01:35,362 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:40397'. Reason: nanny-close
2023-04-04 18:01:35,362 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/rapids/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 202, in _run
    target(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 990, in _run
    asyncio.run(run())
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/ioloop.py", line 687, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 597, in _measure_tick
    def _measure_tick(self):
KeyboardInterrupt
2023-04-04 18:01:35,388 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.120.104.11:40397 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.120.104.11:39172 remote=tcp://10.120.104.11:40397>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 752, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1573, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1262, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1506, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1427, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.120.104.11:40397 after 100 s
2023-04-04 18:01:37,171 - distributed.nanny - INFO - Worker process 1475445 exited with status 1
2023-04-04 18:01:38,564 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-04-04 18:01:39,363 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 18:01:39,365 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1475448 parent=1475407 started daemon>
2023-04-04 18:01:39,572 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1475448 exit status was already read will report exitcode 255
