RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 15:04:19,198 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:45989'
2023-04-04 15:04:19,201 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:43063'
2023-04-04 15:04:20,347 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 15:04:20,347 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 15:04:20,356 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 15:04:20,356 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 15:04:20,602 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 15:04:20,647 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 15:04:21,759 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:36299
2023-04-04 15:04:21,759 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:36299
2023-04-04 15:04:21,759 - distributed.worker - INFO -          dashboard at:        10.120.104.11:46369
2023-04-04 15:04:21,759 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 15:04:21,759 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:21,759 - distributed.worker - INFO -               Threads:                          1
2023-04-04 15:04:21,759 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 15:04:21,759 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-jadp605g
2023-04-04 15:04:21,759 - distributed.worker - INFO - Starting Worker plugin RMMSetup-892ca934-8a9f-45fa-8e7d-d2cff65d3513
2023-04-04 15:04:21,894 - distributed.worker - INFO - Starting Worker plugin PreImport-11b43b55-19b8-490d-a4bd-f6ba99b6690a
2023-04-04 15:04:21,894 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-afe19941-2a6b-4716-82ca-91f20ab5f871
2023-04-04 15:04:21,898 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:21,911 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 15:04:21,911 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:21,913 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 15:04:21,916 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:44635
2023-04-04 15:04:21,916 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:44635
2023-04-04 15:04:21,916 - distributed.worker - INFO -          dashboard at:        10.120.104.11:37911
2023-04-04 15:04:21,916 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 15:04:21,916 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:21,916 - distributed.worker - INFO -               Threads:                          1
2023-04-04 15:04:21,916 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 15:04:21,916 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-v3e7y813
2023-04-04 15:04:21,917 - distributed.worker - INFO - Starting Worker plugin RMMSetup-3dd3f472-f0f0-4b72-a82c-e327cc28c66b
2023-04-04 15:04:22,051 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-97f072a5-f70d-4048-a904-1ca633c3a2e7
2023-04-04 15:04:22,051 - distributed.worker - INFO - Starting Worker plugin PreImport-21a427ac-e888-46ed-afca-dec8edea76ef
2023-04-04 15:04:22,051 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:22,060 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 15:04:22,061 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 15:04:22,062 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 15:04:44,142 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:04:44,143 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:04:44,969 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 15:04:44,969 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 15:04:45,614 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:04:45,627 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:04:45,632 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 15:04:45,636 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 15:04:54,223 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 15:04:54,272 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 15:05:00,965 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.13s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 15:05:00,967 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.13s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 15:05:00,975 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 15:05:00,975 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 15:05:11,005 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:05:11,006 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 15:17:15,657 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:36299. Reason: worker-handle-scheduler-connection-broken
2023-04-04 15:17:15,657 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:45989'. Reason: nanny-close
2023-04-04 15:17:15,658 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:44635. Reason: worker-handle-scheduler-connection-broken
2023-04-04 15:17:15,658 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 15:17:15,659 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:43063'. Reason: nanny-close
2023-04-04 15:17:15,659 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 15:17:15,677 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.120.104.11:43063 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.120.104.11:35358 remote=tcp://10.120.104.11:43063>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 752, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1573, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1262, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1506, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1427, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.120.104.11:43063 after 100 s
2023-04-04 15:17:18,861 - distributed.nanny - WARNING - Worker process still alive after 3.199996490478516 seconds, killing
2023-04-04 15:17:18,861 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-04-04 15:17:19,804 - distributed.nanny - INFO - Worker process 1340747 was killed by signal 9
2023-04-04 15:17:19,805 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 15:17:19,807 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1340750 parent=1340735 started daemon>
